name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

    - name: Heroku Build
      # You may pin to the exact commit or the version.
      # uses: behe/heroku-build@d1420cf172bb918aae4f0081b1c3fba69e1659ad
      uses: behe/heroku-build@v1.1
      with:
        # Name of Heroku application
        app-name: 
        # API key with the deploy role
        api-key: 
        # Directory to upload
        path: # optional, default is .
